version: '3'

services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "25039:3000"
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
      - CORS_HEADERS=Content-Type
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "25040:5000"
    depends_on:
      - backend
    networks:
      - app-network
    environment:
      - NODE_ENV=development
      - BACKEND_URL=http://localhost:25039
    volumes:
      - ./frontend:/app
      - /app/node_modules

networks:
  app-network:
    driver: bridge
